services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: username
      DB_PASSWORD: password
      DB_NAME: recipeze
      DB_PORT: 5432
      DATABASE_URL: localhost
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recipeze
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U username -d recipeze" ]
      interval: 5s
      timeout: 5s
      retries: 5

  sqlc:
    image: sqlc/sqlc
    volumes:
      - .:/src
    working_dir: /src
    command: generate
    profiles:
      - tools

volumes:
  go-modules:
  postgres-data:
