// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const addRecipe = `-- name: AddRecipe :execresult
INSERT INTO recipes (
    url,
    name,
    description
) VALUES (
    $1, $2, $3
)
`

type AddRecipeParams struct {
	Url         pgtype.Text
	Name        pgtype.Text
	Description pgtype.Text
}

func (q *Queries) AddRecipe(ctx context.Context, arg AddRecipeParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, addRecipe, arg.Url, arg.Name, arg.Description)
}

const getRecipeByID = `-- name: GetRecipeByID :one
select id, url, name, description, created_at from recipes where id = $1 LIMIT 1
`

func (q *Queries) GetRecipeByID(ctx context.Context, id int32) (Recipe, error) {
	row := q.db.QueryRow(ctx, getRecipeByID, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getRecipes = `-- name: GetRecipes :many
SELECT id, url, name, description, created_at from recipes
`

func (q *Queries) GetRecipes(ctx context.Context) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, getRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
