CREATE TABLE recipes (
    id SERIAL PRIMARY KEY,
    url VARCHAR(255),
    name VARCHAR(255),
    description text,
    image_url VARCHAR(255),
    likes INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(128) NOT NULL UNIQUE,
    name VARCHAR(128),
    image_url VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE auth_tokens (
    id SERIAL PRIMARY KEY,
    token TEXT NOT NULL UNIQUE,
    email VARCHAR(128) NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP + INTERVAL '30 minutes',
    creator_ip VARCHAR(45)
);

ALTER TABLE auth_tokens 
ADD CONSTRAINT fk_auth_tokens_user 
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;